INSERT INTO CATEGORY(NAME) VALUES ('Cat1')
INSERT INTO CATEGORY(NAME) VALUES ('Cat2')
INSERT INTO CATEGORY(NAME) VALUES ('Cat3')
INSERT INTO CATEGORY(NAME) VALUES ('Cat4') 

INSERT INTO USER (NAME, EMAIL,USER_NAME,PASSWORD,ADDRESS,CITY,POST_NUMBER,REGISTRATED,ROLE,LONGITUDE,LATITUDE,DISTANCE) VALUES('Olja','olja.miljatovic@yahoo.com','Oljica','111','Mise Dimitrijevica 34','Novi Sad','21000',1,1,45.0,15.0,-1)
INSERT INTO USER (NAME, EMAIL,USER_NAME,PASSWORD,ADDRESS,CITY,POST_NUMBER,REGISTRATED,ROLE,LONGITUDE,LATITUDE,DISTANCE) VALUES('Vladimir','vladimir94@gmail.com','vladimir94','222','Sime Milosevica 10','Novi Sad','21000',1,1,44.9,15.1,-1)
