INSERT INTO CATEGORY(NAME) VALUES ('Cat1')
INSERT INTO CATEGORY(NAME) VALUES ('Cat2')
INSERT INTO CATEGORY(NAME) VALUES ('Cat3')
INSERT INTO CATEGORY(NAME) VALUES ('Cat4') 

INSERT INTO USER (NAME, EMAIL,USER_NAME,PASSWORD,ADDRESS,CITY,POST_NUMBER,REGISTRATED,ROLE,LONGITUDE,LATITUDE,DISTANCE,RANDOM_KEY) VALUES('Olja','olja.miljatovic@yahoo.com','Oljica','111','Mise Dimitrijevica 34','Novi Sad','21000',1,2,45.0,15.0,-1,'/')
INSERT INTO USER (NAME, EMAIL,USER_NAME,PASSWORD,ADDRESS,CITY,POST_NUMBER,REGISTRATED,ROLE,LONGITUDE,LATITUDE,DISTANCE,RANDOM_KEY) VALUES('Vladimir','vladimir94@gmail.com','vladimir94','test','Sime Milosevica 10','Novi Sad','21000',1,1,44.9,15.1,-1,'/')

INSERT INTO COMPANY_CATEGORY(COMPANY_ID,CATEGORY_ID) VALUES (1,2)
INSERT INTO COMPANY_CATEGORY(COMPANY_ID,CATEGORY_ID) VALUES (1,3)
INSERT INTO COMPANY_CATEGORY(COMPANY_ID,CATEGORY_ID) VALUES (1,4) 
